server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: tuvia
    password: 1
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
externalApi:
  QuestionsAndEmployeeService:
    url: localhost:8080




